name: animated_box_decoration
description: Lets you smoothly animate between two BoxDecoration.
version: 0.0.7
repository: https://github.com/KevinVan720/animated_box_decoration

environment:
  sdk: ">=2.16.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

